# Generated by Django 5.0.4 on 2024-04-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
